// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekhaneDataAccesLayer.Context;

#nullable disable

namespace YemekhaneDataAccesLayer.Migrations
{
    [DbContext(typeof(YemekhaneContext))]
    [Migration("20250804083241_mm33")]
    partial class mm33
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.Admin", b =>
                {
                    b.Property<int>("adminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adminID"));

                    b.Property<string>("adminEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminIsim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminID");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.Calisan", b =>
                {
                    b.Property<int>("calisanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("calisanID"));

                    b.Property<bool>("aktiflik")
                        .HasColumnType("bit");

                    b.Property<string>("calisanGorevi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calisanIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calisanKartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calisanSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gecisSayısı")
                        .HasColumnType("int");

                    b.Property<string>("sicil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("calisanID");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.GirisLoglari", b =>
                {
                    b.Property<int>("GirisLoglariId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GirisLoglariId"));

                    b.Property<bool>("Basarili")
                        .HasColumnType("bit");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GirisZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("GirisLoglariId");

                    b.HasIndex("CalisanId");

                    b.ToTable("girisLoglar");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.Okutmalar", b =>
                {
                    b.Property<int>("OkutmalarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OkutmalarID"));

                    b.Property<DateTime>("OkutmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("aktif")
                        .HasColumnType("bit");

                    b.Property<int>("calisanID")
                        .HasColumnType("int");

                    b.Property<int>("gecisCount")
                        .HasColumnType("int");

                    b.Property<bool>("jokerGecis")
                        .HasColumnType("bit");

                    b.Property<int>("jokerGecisCount")
                        .HasColumnType("int");

                    b.HasKey("OkutmalarID");

                    b.HasIndex("calisanID");

                    b.ToTable("Okutmalar");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.YemekhaneCalisan", b =>
                {
                    b.Property<int>("yemekhaneCalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("yemekhaneCalisanId"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("kullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("yemekhaneCalisanId");

                    b.ToTable("yemekhaneCalisanlar");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.GirisLoglari", b =>
                {
                    b.HasOne("YemekhaneEntityLayer.Entities.YemekhaneCalisan", "Calisan")
                        .WithMany("GirisLoglari")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.Okutmalar", b =>
                {
                    b.HasOne("YemekhaneEntityLayer.Entities.Calisan", "calisan")
                        .WithMany("Okutmalar")
                        .HasForeignKey("calisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("calisan");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.Calisan", b =>
                {
                    b.Navigation("Okutmalar");
                });

            modelBuilder.Entity("YemekhaneEntityLayer.Entities.YemekhaneCalisan", b =>
                {
                    b.Navigation("GirisLoglari");
                });
#pragma warning restore 612, 618
        }
    }
}
